package:
  name: plotly
  version: !!str 1.6.10

source:
  fn: plotly-1.6.10.tar.gz
  url: https://pypi.python.org/packages/source/p/plotly/plotly-1.6.10.tar.gz
  md5: c9855afc57ee6c0b019be24d165f1846
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - plotly = plotly:main
    #
    # Would create an entry point called plotly that calls plotly.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
    - pytz

  run:
    - python
    - requests
    - six
    - pytz

test:
  # Python imports
  imports:
    - plotly

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://plot.ly/api/python
  license: MIT
  summary: 'Python plotting library for collaborative, interactive, publication-quality graphs.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
